### ISSUE TITLE
feat(Workshop CP): Create Vehicles Tab

### ISSUE THREAD

**Issue by SaiFi0102** [ParaLogicTech/erpnext#235]
### Table Columns

- Repair Order (`project`) (Link to Project)
- Model (`applies_to_variant_of_name or applies_to_item_name`)
- Vehicle (`vehicle_license_plate` or `vehicle_chassis_no`) (Link to Vehicle)
- Customer (`customer_name`) (Link to Customer)
- Voice of Customer (`project_name`)
- Status (not yet implemented, leave empty)
- Tasks (not yet implemented, leave empty)
- Expected Delivery (`expected_delivery_date` + `expected_delivery_time`) (Default date formatting, time formatting as `h:mm a`)
- (Action button column without a label)

### API

- In `workshop_cp.py`
- Source from `tabProject`
- Only fetch Repair Orders with `vehicle_status` == "In Workshop"
- Should take filters as argument
- Should take order by as argument

### Action Buttons

- Create Task (is not ready)
- Create Tasks from Template (is not ready and template tasks not created)
- Mark as Ready (all tasks completed)
- Re-Open (is ready)

**Comment by mariafurqan** [comment]
![Image](https://github.com/ParaLogicTech/erpnext/assets/58623315/e9a8e391-c154-4862-98dd-4cd03f7418ae)

**Comment by mariafurqan** [comment]
![Image](https://github.com/ParaLogicTech/erpnext/assets/58623315/56c410bc-d903-45ac-969a-500c842d4236)

**Comment by mariafurqan** [comment]
![Image](https://github.com/ParaLogicTech/erpnext/assets/58623315/2a11e067-2581-4259-8e93-76adadff6054)
